### ISSUE TITLE
Collecting asynchronous collections

### ISSUE THREAD

**Issue by Ginden** [tc39/proposal-async-iteration#107]
We have multiple ways to collect synchronous iterables - like `Array.from`, `Promise.all`, `new Set(iterable)` etc.

Though, the only way to consume asynchronous iterable is currently single syntax construct or manual consumption. I believe that's a serious flaw that would significantly slow down adoption of async iterators.

**Comment by domenic** [comment]
You're welcome to work on a new proposal for your new use case. It's out of scope of this proposal.
