### ISSUE TITLE
Add a asynchronous version of destructuring

### ISSUE THREAD

**Issue by dou4cc** [tc39/proposal-async-iteration#123]
We need `let {a: await [a]} = {a: iterable}` to `let {a: [a]} = {a: iterable}` like `for await(let a of iterable)` to `for(let a of iterable)`.

**Comment by domenic** [comment]
That sounds like a separate proposal, not an issue with this proposal. Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals
