### ISSUE TITLE
%AsyncFromSyncIteratorPrototype%.throw and return will not behave correctly

### ISSUE THREAD

**Issue by caitp** [tc39/proposal-async-iteration#60]
%AsyncFromSyncIteratorPrototype%.throw() will not resume a sync generator from an appropriate exception handler, and %AsyncFromSyncIteratorPrototype%.return() will not close its sync iterator.

Instead, they're both written to call `IteratorNext(syncIterator, value)`, without delegating to the appropriate methods (if any), or using a default behaviour if not present.

**Comment by domenic** [comment]
Thanks. For some reason I thought this would work when writing it, but I can't remember the reasoning now, and it seems clearly wrong... strange. I should have left a comment or note explaining to my future self :(.
