### ISSUE TITLE
Two issues with GeneratorYield in the context of yield*

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/proposal-async-iteration#86]
@ajklein and I found two issues with the proposed version of [`GeneratorYield`](https://tc39.github.io/proposal-async-iteration/#sec-generatoryield) and how it's used in the evaluation of `yield*`.  What is special about the `yield*` use case is the fact that the inner iterator result (`innerResult` in 2.2.1.6), which is passed to `GeneratorYield`, may be a user-created object.

1. Getting this object's `value` or `done` property may throw, but `GeneratorYield` fails to account for abrupt completions of `IteratorValue` and `IteratorComplete`.

2. By the time `GeneratorYield` gets called, the object's `done` property has already been retrieved, e.g. in 2.2.1.6.a.v.  This means that `yield*` will observably `[[Get]]` the `done` property twice, which I think is incomprehensible from a user perspective.

**Comment by arai-a** [comment]
seems to be fixed by https://github.com/tc39/proposal-async-iteration/pull/87 ?
