### ISSUE TITLE
unnamed expressions

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-async-iteration#95]
the current proposal does not set an optional Binding Identifier for AsyncGeneratorExpression.

Ref https://tc39.github.io/proposal-async-iteration/#prod-AsyncGeneratorExpression

Is this intended? (I'm writing tests accordingly the answer).

**Comment by domenic** [comment]
I'm sorry, I don't really understand. That section is mostly done with analogy to GeneratorExpression. Is this perhaps covered by https://tc39.github.io/proposal-async-iteration/#misc-patches , i.e. the general places that need to be patched to also consider AsyncGeneratorExpression?

Could you share what spec text you think might be missing, and how it affects a test result?
